default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: memory_and_record_development


test:
  <<: *default
  database: memory_test

production:
  <<: *default
  database: memory_and_record_development
  username: memory
  password: <%= ENV["MEMORY_DATABASE_PASSWORD"] %>
